name: Build ImmortalWrt for Xiaomi R3G

on:
  workflow_dispatch: # 允许手动点击运行
  push:
    tags:
      - 'v*' # 当推送 v 开头的标签（如 v1.0, v24.10.1）时自动触发

jobs:
  build:
    runs-on: ubuntu-24.04 # 运行环境
    permissions:
      contents: write # 赋予写入权限，以便创建 Release 和上传文件

    steps:
      - name: 检出仓库代码 (Checkout Repository)
        uses: actions/checkout@v4

      - name: 安装系统依赖 (Install Dependencies)
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
            libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
            ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
            python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

      - name: 克隆 ImmortalWrt 源码 (Clone ImmortalWrt Source)
        run: |
          git clone -b openwrt-24.10 https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 加载自定义配置文件 (Load Custom Configure)
        run: |
          cp .config immortalwrt/.config
          cd
